#!/bin/bash

cd /home/robert/canon-pdriver
# exract the .gz file
#tar -xvzf linux-UFRII-drv-v620-m17n-20.tar.gz

# check if X is running,
if [ -n "$DISPLAY" ]; then
	# X is running install
	./install.sh
else
	# X is not running cannot install
	echo "X is not running"
	echo "Start X "
	echo "run /home/robert/canon-pdriver/install.sh"
fi
exit 0;
