#!/bin/bash
# install.sh runs apt so it cannot be called directly from postinst
cd /home/robert/canon-drv
# exract the .gz file
#tar -xvzf linux-UFRII-drv-v620-m17n-20.tar.gz

# check if X is running,
if [ -n "$DISPLAY" ]; then
	# X is running install
	./install.sh
else
	# X is not running cannot install
	echo "X is not running, read the following unstructions for installing:"
	echo "Start X "
	echo "then run /home/robert/canon-drv/install.sh in a terminal as root"
fi
exit 0;
