#!/bin/bash
# install.sh runs apt so it cannot be called directly from postinst
cd /home/robert/canon-drv
# exract the .gz file
#tar -xvzf linux-UFRII-drv-v620-m17n-20.tar.gz

# print instructions to run install.sh
echo "Start X windows"
echo "then run /home/robert/canon-drv/install.sh as root to install the drivers"
exit 0;
